# Generated by Django 5.1 on 2024-08-28 14:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todo_backend", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="status",
            new_name="task_status",
        ),
    ]
